#pragma once



enum EDIT_TYPE
{
	EDIT_TYPE_CREATE_ROOMNAME,
	EDIT_TYPE_CREATE_PASSWORD,
	EDIT_TYPE_WAITING_ROOM_CHATTING,
	EDIT_TYPE_WAITING_ROOM_INGAME_CHATTING,
	EDIT_TYPE_END
};


enum RES_TYPE
{
	RES_TYPE_BACKGROUND,
	RES_TYPE_SELECT_CHARACTER,
	RES_TYPE_WAITING_ROOM,
	RES_TYPE_WAITING_ROOM_INFO,
	RES_TYPE_WAITING_ROOM_INGAME,
	RES_TYPE_CREATE_ROOM,
	RES_TYPE_BUTTON_JOIN,
	RES_TYPE_BUTTON_EXIT,
	RES_TYPE_BUTTON_CHANGECHENNEL,
	RES_TYPE_BUTTON_CREATEROOM,
	RES_TYPE_BUTTON_JOINROOM,
	RES_TYPE_BUTTON_VISITORINFORMATION,
	RES_TYPE_BUTTON_CREATE_ROOM_EXCUTE,
	RES_TYPE_BUTTON_CREATE_ROOM_CANCLE,
	RES_TYPE_CHARACTER_BANANA,
	RES_TYPE_CHARACTER_BEANCAKE,
	RES_TYPE_CHARACTER_DONG,
	RES_TYPE_CHARACTER_EGG,
	RES_TYPE_CHARACTER_EGGHALF,
	RES_TYPE_CHARACTER_GARLIC,
	RES_TYPE_CHARACTER_GRAPE,
	RES_TYPE_CHARACTER_KIMCHI,
	RES_TYPE_CHARACTER_LETTUCE,
	RES_TYPE_CHARACTER_MUSHROOM,
	RES_TYPE_CHARACTER_ORANGE,
	RES_TYPE_CHARACTER_ONION,
	RES_TYPE_CHARACTER_PEPPER,
	RES_TYPE_CHARACTER_RADISH,
	RES_TYPE_CHARACTER_RICEROCK,
	RES_TYPE_CHARACTER_SALAD,
	RES_TYPE_CHARACTER_TOMATO,
	RES_TYPE_END
};



enum UI_TYPE
{
	UI_TYPE_SELECT_CHARACTER,
	UI_TYPE_WAITING_ROOM,
	UI_TYPE_WAITING_ROOM_INFO,
	UI_TYPE_WAITING_ROOM_INGAME,
	UI_TYPE_BUTTON_JOIN,
	UI_TYPE_BUTTON_EXIT,
	UI_TYPE_BUTTON_CHANGECHENNEL,
	UI_TYPE_BUTTON_CREATEROOM,
	UI_TYPE_BUTTON_JOINROOM,
	UI_TYPE_BUTTON_VISITORINFORMATION,
	UI_TYPE_CHARACTER_BANANA = 3000,
	UI_TYPE_CHARACTER_BEANCAKE,
	UI_TYPE_CHARACTER_DONG,
	UI_TYPE_CHARACTER_EGG,
	UI_TYPE_CHARACTER_EGGHALF,
	UI_TYPE_CHARACTER_GARLIC,
	UI_TYPE_CHARACTER_GRAPE,
	UI_TYPE_CHARACTER_KIMCHI,
	UI_TYPE_CHARACTER_LETTUCE,
	UI_TYPE_CHARACTER_MUSHROOM,
	UI_TYPE_CHARACTER_ONION,
	UI_TYPE_CHARACTER_ORANGE,
	UI_TYPE_CHARACTER_PEPPER,
	UI_TYPE_CHARACTER_RADISH,
	UI_TYPE_CHARACTER_RICEROCK,
	UI_TYPE_CHARACTER_SALAD,
	UI_TYPE_CHARACTER_TOMATO,
	UI_TYPE_USER_LIST,
	UI_TYPE_ROOM_LIST,
	UI_TYPE_CREATE_ROOM,
	UI_TYPE_BUTTON_CREATE_ROOM_EXCUTE,
	UI_TYPE_BUTTON_CREATE_ROOM_CANCLE,
	UI_TYPE_END
};



